export const FETCH_BOOKS_REQUEST = "FETCH_BOOKS_REQUEST";
export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS";
export const FETCH_BOOKS_FAILURE = "FETCH_BOOKS_FAILURE";
export const UPDATE_COLUMN_ORDER = "UPDATE_COLUMN_ORDER";
export const SORT_BOOKS = "SORT_BOOKS";
export const TOGGLE_COLUMN_VISIBILITY = "TOGGLE_COLUMN_VISIBILITY";
